#!/usr/bin/env python3
"""Runtime helper for the vLLM + LMCache MP filesystem-L2 baseline."""

from __future__ import annotations

import argparse
import json
import os
import shlex
import socket
import sys
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


def _env(name: str, default: str) -> str:
    return os.environ.get(name, default)


def _env_bool(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.lower() in {"1", "true", "yes", "on"}


def _as_abs(repo_root: Path, value: str | Path) -> Path:
    path = Path(value)
    if not path.is_absolute():
        path = repo_root / path
    return path.resolve()


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _runtime_load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _runtime_get(runtime: dict[str, Any], dotted_key: str) -> Any:
    value: Any = runtime
    for part in dotted_key.split("."):
        if not isinstance(value, dict):
            raise KeyError(dotted_key)
        value = value[part]
    return value


def _bash_env_line(key: str, value: object) -> str:
    return f"export {key}={shlex.quote(str(value))}"


def _normalize_engine_args(
    raw_args: list[str],
    *,
    engine: str,
    disable_radix_cache: bool,
    enable_metrics: bool,
) -> list[str]:
    extra_args: list[str] = []
    index = 0
    while index < len(raw_args):
        arg = raw_args[index]
        if engine == "vllm" and arg == "--tp":
            if index + 1 >= len(raw_args):
                raise SystemExit("--tp requires a value")
            extra_args.extend(["--tensor-parallel-size", raw_args[index + 1]])
            index += 2
            continue
        if engine == "vllm" and arg in {"--disable-radix-cache", "--enable-metrics"}:
            index += 1
            continue
        if engine == "sglang" and arg == "--tensor-parallel-size":
            if index + 1 >= len(raw_args):
                raise SystemExit("--tensor-parallel-size requires a value")
            extra_args.extend(["--tp", raw_args[index + 1]])
            index += 2
            continue
        extra_args.append(arg)
        index += 1

    if engine == "sglang":
        if disable_radix_cache:
            extra_args.append("--disable-radix-cache")
        if enable_metrics:
            extra_args.append("--enable-metrics")
    return extra_args


def _build_l2_adapter(l2_type: str, l2_path: Path, use_odirect: bool, workers: str) -> dict[str, Any]:
    adapter: dict[str, Any] = {"type": l2_type, "base_path": str(l2_path)}
    if use_odirect:
        adapter["use_odirect"] = True
    if workers:
        adapter["num_thread"] = int(workers)
    return adapter


def _build_vllm_kv_transfer_config(
    host: str,
    port: int,
    transfer_mode: str,
    connector_module_path: str,
) -> dict[str, Any]:
    config: dict[str, Any] = {
        "kv_connector": "LMCacheMPConnector",
        "kv_role": "kv_both",
        "kv_connector_extra_config": {
            "lmcache.mp.host": host,
            "lmcache.mp.port": port,
            "lmcache.mp.mp_transfer_mode": transfer_mode,
        },
    }
    if connector_module_path:
        config["kv_connector_module_path"] = connector_module_path
    return config


def _write_disk_prompt(path: Path, prompt_id: str, warmup_prompt_id: str) -> None:
    repeat = int(_env("GE_DISK_PROMPT_REPEAT", "256"))
    max_tokens = int(_env("GE_DISK_PROMPT_MAX_TOKENS", "128"))
    lines = [
        (
            f"Cache persistence calibration line {index:04d}: "
            "GoldenExperience disk-offload validation keeps this deterministic prefix stable. "
            "Natalia April clips equals 48 and May clips equals half of April. "
            "This repeated text exists only to make the prompt large enough for KV caching."
        )
        for index in range(repeat)
    ]
    user_content = (
        "Read the following deterministic reference block. Do not summarize the block.\n\n"
        + "\n".join(lines)
        + "\n\nQuestion: Natalia sold clips to 48 of her friends in April, and then she sold "
        "half as many clips in May. How many clips did Natalia sell altogether in April "
        "and May? End with exactly one line formatted as: Final answer: <number>."
    )
    manifest = {
        "default_prompt_id": prompt_id,
        "prompts": [
            {
                "id": prompt_id,
                "dataset": "synthetic-long-prefix",
                "split": "disk-offload",
                "source": "generated by run_vllm_lmcache_mp_l2_baseline.sh",
                "expected_final_answer": "72",
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a careful math solver. Use the reference only as context.",
                    },
                    {"role": "user", "content": user_content},
                ],
                "generation": {"max_tokens": max_tokens, "temperature": 0},
            },
            {
                "id": warmup_prompt_id,
                "dataset": "synthetic",
                "split": "warmup",
                "source": "short unrelated warmup prompt for engine stabilization",
                "expected_final_answer": "OK",
                "messages": [
                    {"role": "system", "content": "You are a concise assistant."},
                    {"role": "user", "content": "Reply with exactly: OK"},
                ],
                "generation": {"max_tokens": 8, "temperature": 0},
            },
        ],
    }
    _write_json(path, manifest)


def _write_lmcache_recorded_config(runtime: dict[str, Any]) -> None:
    config_path = Path(runtime["paths"]["config_file"])
    metadata = runtime["metadata"]
    if metadata["kv_backend"] == "mp":
        text = f"""# Generated by scripts/kv_baseline/run_vllm_lmcache_mp_l2_baseline.sh
kv_backend: mp
engine: vllm
chunk_size: {metadata["chunk_size"]}
hash_algorithm: {metadata["hash_algorithm"]}
lmcache_mp:
  host: {metadata["lmcache_mp"]["host"]}
  bind_host: {metadata["lmcache_mp"]["bind_host"]}
  port: {metadata["lmcache_mp"]["port"]}
  http_host: {metadata["lmcache_mp"]["http_host"]}
  http_port: {metadata["lmcache_mp"]["http_port"]}
  prometheus_port: {metadata["lmcache_mp"]["prometheus_port"]}
  l1_size_gb: {metadata["lmcache_mp"]["l1_size_gb"]}
  l1_init_size_gb: {metadata["lmcache_mp"]["l1_init_size_gb"]}
  eviction_policy: {metadata["lmcache_mp"]["eviction_policy"]}
  l2_store_policy: {metadata["lmcache_mp"]["l2_store_policy"]}
  l2_adapter_json: '{metadata["lmcache_mp"]["l2_adapter_json"]}'
vllm:
  kv_transfer_config: '{metadata["vllm_kv_transfer_config"]}'
"""
    else:
        text = f"""# Generated by scripts/kv_baseline/run_vllm_lmcache_mp_l2_baseline.sh
kv_backend: legacy
engine: sglang
chunk_size: {metadata["chunk_size"]}
local_cpu: {str(metadata["local_cpu_enabled"]).lower()}
max_local_cpu_size: {metadata["local_cpu_gb"]}
local_disk: "file://{metadata["kv_cache_dir"]}"
max_local_disk_size: {metadata["local_disk_gb"]}
use_layerwise: true
save_decode_cache: {str(metadata["save_decode_cache"]).lower()}
pre_caching_hash_algorithm: {metadata["hash_algorithm"]}
"""
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(text, encoding="utf-8")


def prepare(args: argparse.Namespace) -> int:
    repo_root = Path(args.repo_root).resolve()
    raw_engine_args = list(args.engine_args)
    if raw_engine_args and raw_engine_args[0] == "--":
        raw_engine_args = raw_engine_args[1:]

    kv_backend = _env("GE_KV_BACKEND", "mp")
    engine = _env("GE_ENGINE", "vllm")
    if kv_backend not in {"mp", "legacy"}:
        raise SystemExit(f"GE_KV_BACKEND must be mp or legacy, got: {kv_backend}")
    if engine not in {"vllm", "sglang"}:
        raise SystemExit(f"GE_ENGINE must be vllm or sglang, got: {engine}")
    if kv_backend == "mp" and engine != "vllm":
        raise SystemExit("GE_KV_BACKEND=mp currently requires GE_ENGINE=vllm.")
    if kv_backend == "legacy" and engine != "sglang":
        raise SystemExit("GE_KV_BACKEND=legacy only supports GE_ENGINE=sglang.")

    force_disk_offload = _env_bool("GE_FORCE_DISK_OFFLOAD", True)
    disable_radix_cache = _env_bool("GE_DISABLE_RADIX_CACHE", True)
    enable_metrics = _env_bool("GE_ENABLE_ENGINE_METRICS", _env_bool("GE_ENABLE_SGLANG_METRICS", True))
    wait_for_ready_log = _env_bool("GE_WAIT_FOR_READY_LOG", engine == "sglang")
    include_usage = _env_bool("GE_INCLUDE_USAGE", True)
    warmup_before_measure = _env_bool("GE_WARMUP_BEFORE_MEASURE", True)
    save_decode_cache = _env_bool("GE_SAVE_DECODE_CACHE", False)

    run_id = _env("GE_RUN_ID", datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ"))
    run_dir = Path(_env("GE_RUN_DIR", f"artifacts/kv_baseline/{run_id}"))
    cache_dir = Path(_env("GE_KV_CACHE_DIR", str(run_dir / "cache")))
    log_dir = run_dir / "logs"
    request_dir = run_dir / "requests"
    metrics_dir = run_dir / "metrics"
    config_file = Path(_env("GE_LMCACHE_CONFIG_FILE", str(run_dir / "lmc_config.yaml")))
    prompt_file_was_set = "GE_PROMPT_FILE" in os.environ
    disk_prompt_id = _env("GE_DISK_PROMPT_ID", "kv_disk_long_prefix")
    warmup_prompt_id = _env("GE_WARMUP_PROMPT_ID", "kv_baseline_warmup")
    if force_disk_offload and not prompt_file_was_set:
        prompt_file = run_dir / "prompts.json"
        prompt_id = disk_prompt_id
    else:
        prompt_file = Path(_env("GE_PROMPT_FILE", "configs/kv_baseline_prompts.json"))
        prompt_id = _env("GE_PROMPT_ID", "gsm8k_natalia_clips")

    local_cpu_enabled = _env_bool("GE_KV_LOCAL_CPU_ENABLED", not force_disk_offload)
    local_cpu_gb = float(_env("GE_KV_LOCAL_CPU_GB", "0" if force_disk_offload else "10"))
    local_disk_gb = float(_env("GE_KV_LOCAL_DISK_GB", "100"))
    lmcache_mp_l2_dir = Path(_env("GE_LMCACHE_MP_L2_DIR", str(cache_dir)))

    run_dir_abs = _as_abs(repo_root, run_dir)
    cache_dir_abs = _as_abs(repo_root, cache_dir)
    lmcache_mp_l2_dir_abs = _as_abs(repo_root, lmcache_mp_l2_dir)
    kv_cache_dir_abs = lmcache_mp_l2_dir_abs if kv_backend == "mp" else cache_dir_abs
    prompt_file_abs = _as_abs(repo_root, prompt_file)
    config_file_abs = _as_abs(repo_root, config_file)

    for path in (run_dir_abs, cache_dir_abs, lmcache_mp_l2_dir_abs, log_dir, request_dir, metrics_dir):
        _as_abs(repo_root, path).mkdir(parents=True, exist_ok=True)
    config_file_abs.parent.mkdir(parents=True, exist_ok=True)

    if force_disk_offload and not prompt_file_was_set:
        _write_disk_prompt(prompt_file_abs, disk_prompt_id, warmup_prompt_id)

    chunk_size = int(_env("GE_KV_CHUNK_SIZE", "16"))
    hash_algorithm = _env("GE_LMCACHE_HASH_ALGORITHM", "builtin")
    l2_adapter = _build_l2_adapter(
        _env("GE_LMCACHE_MP_L2_ADAPTER_TYPE", "fs"),
        lmcache_mp_l2_dir_abs,
        _env_bool("GE_LMCACHE_MP_L2_USE_ODIRECT", False),
        _env("GE_LMCACHE_MP_L2_NUM_WORKERS", ""),
    )
    lmcache_mp_host = _env("GE_LMCACHE_MP_HOST", "127.0.0.1")
    lmcache_mp_port = int(_env("GE_LMCACHE_MP_PORT", "6555"))
    lmcache_mp_connect_host = _env("GE_LMCACHE_MP_CONNECT_HOST", lmcache_mp_host)
    lmcache_mp_http_host = _env("GE_LMCACHE_MP_HTTP_HOST", "127.0.0.1")
    lmcache_mp_prometheus_port = int(_env("GE_LMCACHE_MP_PROMETHEUS_PORT", "9090"))
    vllm_kv_transfer_config = _build_vllm_kv_transfer_config(
        lmcache_mp_connect_host,
        lmcache_mp_port,
        _env("GE_LMCACHE_MP_TRANSFER_MODE", "auto"),
        _env("GE_VLLM_KV_CONNECTOR_MODULE_PATH", ""),
    )
    l2_adapter_json = json.dumps(l2_adapter, separators=(",", ":"))
    vllm_kv_transfer_config_json = json.dumps(vllm_kv_transfer_config, separators=(",", ":"))
    extra_engine_args = _normalize_engine_args(
        raw_engine_args,
        engine=engine,
        disable_radix_cache=disable_radix_cache,
        enable_metrics=enable_metrics,
    )

    model_path = _env("GE_MODEL_PATH", "Qwen/Qwen3-8B")
    model_name = _env("GE_MODEL_NAME", model_path)
    host = _env("GE_HOST", "0.0.0.0")
    client_host = _env("GE_CLIENT_HOST", "127.0.0.1")
    port = int(_env("GE_PORT", "30000"))
    base_url = f"http://{client_host}:{port}"
    require_reuse_evidence = _env_bool("GE_REQUIRE_REUSE_EVIDENCE", force_disk_offload)

    metadata = {
        "run_id": run_id,
        "run_dir": str(run_dir),
        "mode": _env("GE_BASELINE_MODE", "restart"),
        "kv_backend": kv_backend,
        "engine": engine,
        "model_path": model_path,
        "model_name": model_name,
        "base_url": base_url,
        "prompt_file": str(prompt_file),
        "prompt_id": prompt_id,
        "lmcache_config_file": str(config_file),
        "kv_cache_dir": str(kv_cache_dir_abs),
        "chunk_size": chunk_size,
        "force_disk_offload": force_disk_offload,
        "local_cpu_enabled": local_cpu_enabled,
        "local_cpu_gb": local_cpu_gb,
        "local_disk_gb": local_disk_gb,
        "save_decode_cache": save_decode_cache,
        "hash_algorithm": hash_algorithm,
        "disk_prompt_id": disk_prompt_id,
        "disk_prompt_repeat": int(_env("GE_DISK_PROMPT_REPEAT", "256")),
        "disk_prompt_max_tokens": int(_env("GE_DISK_PROMPT_MAX_TOKENS", "128")),
        "generated_disk_prompt": force_disk_offload and not prompt_file_was_set,
        "lmcache_mp": {
            "enabled": kv_backend == "mp",
            "host": lmcache_mp_host,
            "bind_host": _env("GE_LMCACHE_MP_BIND_HOST", lmcache_mp_host),
            "connect_host": lmcache_mp_connect_host,
            "port": lmcache_mp_port,
            "http_host": lmcache_mp_http_host,
            "http_port": int(_env("GE_LMCACHE_MP_HTTP_PORT", "8080")),
            "prometheus_port": lmcache_mp_prometheus_port,
            "l1_size_gb": float(_env("GE_LMCACHE_MP_L1_GB", "4")),
            "l1_init_size_gb": float(_env("GE_LMCACHE_MP_L1_INIT_GB", "1")),
            "eviction_policy": _env("GE_LMCACHE_MP_EVICTION_POLICY", "noop"),
            "l2_store_policy": _env("GE_LMCACHE_MP_L2_STORE_POLICY", "skip_l1"),
            "l2_adapter_json": l2_adapter_json,
            "l2_dir": str(lmcache_mp_l2_dir_abs),
            "transfer_mode": _env("GE_LMCACHE_MP_TRANSFER_MODE", "auto"),
            "lookup_hash_log": _env_bool("GE_LMCACHE_MP_LOOKUP_HASH_LOG", True),
            "lookup_hash_log_dir": str(
                _as_abs(repo_root, _env("GE_LMCACHE_MP_LOOKUP_HASH_LOG_DIR", str(run_dir / "lookup_hashes")))
            ),
        },
        "vllm_kv_transfer_config": vllm_kv_transfer_config_json,
        "disable_radix_cache": disable_radix_cache,
        "enable_engine_metrics": enable_metrics,
        "include_usage": include_usage,
        "wait_for_ready_log": wait_for_ready_log,
        "ready_log_pattern": _env("GE_READY_LOG_PATTERN", "The server is fired up and ready to roll!"),
        "warmup_before_measure": warmup_before_measure,
        "warmup_prompt_id": warmup_prompt_id,
        "require_reuse_evidence": require_reuse_evidence,
        "created_unix": time.time(),
    }

    if metadata["lmcache_mp"]["lookup_hash_log"]:
        Path(metadata["lmcache_mp"]["lookup_hash_log_dir"]).mkdir(parents=True, exist_ok=True)

    lmcache_mp_args = [
        "server",
        "--host",
        metadata["lmcache_mp"]["bind_host"],
        "--port",
        str(metadata["lmcache_mp"]["port"]),
        "--http-host",
        metadata["lmcache_mp"]["http_host"],
        "--http-port",
        str(metadata["lmcache_mp"]["http_port"]),
        "--prometheus-port",
        str(metadata["lmcache_mp"]["prometheus_port"]),
        "--chunk-size",
        str(chunk_size),
        "--hash-algorithm",
        hash_algorithm,
        "--l1-size-gb",
        str(metadata["lmcache_mp"]["l1_size_gb"]),
        "--l1-init-size-gb",
        str(metadata["lmcache_mp"]["l1_init_size_gb"]),
        "--eviction-policy",
        metadata["lmcache_mp"]["eviction_policy"],
        "--l2-store-policy",
        metadata["lmcache_mp"]["l2_store_policy"],
        "--l2-adapter",
        l2_adapter_json,
    ]
    if metadata["lmcache_mp"]["lookup_hash_log"]:
        lmcache_mp_args.extend(["--lookup-hash-log-dir", metadata["lmcache_mp"]["lookup_hash_log_dir"]])
    if os.environ.get("GE_LMCACHE_MP_EXTRA_ARGS"):
        lmcache_mp_args.extend(shlex.split(os.environ["GE_LMCACHE_MP_EXTRA_ARGS"]))

    commands = {
        "lmcache": lmcache_mp_args,
        "vllm": [
            "serve",
            model_path,
            "--host",
            host,
            "--port",
            str(port),
            "--served-model-name",
            model_name,
            "--kv-transfer-config",
            vllm_kv_transfer_config_json,
            *extra_engine_args,
        ],
        "sglang-legacy": extra_engine_args,
    }
    paths = {
        "repo_root": str(repo_root),
        "run_dir": str(_as_abs(repo_root, run_dir)),
        "log_dir": str(_as_abs(repo_root, log_dir)),
        "request_dir": str(_as_abs(repo_root, request_dir)),
        "metrics_dir": str(_as_abs(repo_root, metrics_dir)),
        "config_file": str(config_file_abs),
        "prompt_file": str(prompt_file_abs),
        "cache_dir": str(kv_cache_dir_abs),
        "runtime_json": str(run_dir_abs / "runtime.json"),
        "runtime_env": str(run_dir_abs / "runtime.env"),
    }
    runtime = {
        "metadata": metadata,
        "paths": paths,
        "commands": commands,
        "tools": {
            "python": _env("PYTHON_BIN", "python3"),
            "vllm": _env("VLLM_BIN", "vllm"),
            "lmcache": _env("LMCACHE_BIN", "lmcache"),
        },
        "timeouts": {
            "server_start": float(_env("GE_SERVER_START_TIMEOUT_SEC", "900")),
            "request": float(_env("GE_REQUEST_TIMEOUT_SEC", "600")),
            "after_request_sleep": float(_env("GE_AFTER_REQUEST_SLEEP_SEC", "10")),
            "after_warmup_sleep": float(_env("GE_AFTER_WARMUP_SLEEP_SEC", "1")),
        },
        "control": {
            "keep_server_after_reuse": _env_bool("GE_KEEP_SERVER_AFTER_REUSE", False),
            "keep_lmcache_mp_after_run": _env_bool(
                "GE_KEEP_LMCACHE_MP_AFTER_RUN",
                _env_bool("GE_KEEP_SERVER_AFTER_REUSE", False),
            ),
        },
    }

    _write_lmcache_recorded_config(runtime)
    _write_json(run_dir_abs / "metadata.json", metadata)
    _write_json(Path(paths["runtime_json"]), runtime)
    env_lines = [
        _bash_env_line("GE_RUNTIME_JSON", paths["runtime_json"]),
        _bash_env_line("GE_RUNTIME_RUN_DIR", paths["run_dir"]),
        _bash_env_line("GE_RUNTIME_LOG_DIR", paths["log_dir"]),
        _bash_env_line("GE_RUNTIME_REQUEST_DIR", paths["request_dir"]),
        _bash_env_line("GE_RUNTIME_METRICS_DIR", paths["metrics_dir"]),
        _bash_env_line("GE_RUNTIME_CONFIG_FILE", paths["config_file"]),
        _bash_env_line("GE_RUNTIME_PROMPT_FILE", paths["prompt_file"]),
        _bash_env_line("GE_RUNTIME_PROMPT_ID", prompt_id),
        _bash_env_line("GE_RUNTIME_MODEL_PATH", model_path),
        _bash_env_line("GE_RUNTIME_MODEL_NAME", model_name),
        _bash_env_line("GE_RUNTIME_HOST", host),
        _bash_env_line("GE_RUNTIME_PORT", port),
        _bash_env_line("GE_RUNTIME_BASE_URL", base_url),
        _bash_env_line("GE_RUNTIME_KV_BACKEND", kv_backend),
        _bash_env_line("GE_RUNTIME_ENGINE", engine),
        _bash_env_line("GE_RUNTIME_BASELINE_MODE", metadata["mode"]),
        _bash_env_line("GE_RUNTIME_FORCE_DISK_OFFLOAD", int(force_disk_offload)),
        _bash_env_line("GE_RUNTIME_REQUIRE_REUSE_EVIDENCE", int(require_reuse_evidence)),
        _bash_env_line("GE_RUNTIME_ENABLE_METRICS", int(enable_metrics)),
        _bash_env_line("GE_RUNTIME_INCLUDE_USAGE", int(include_usage)),
        _bash_env_line("GE_RUNTIME_WARMUP_BEFORE_MEASURE", int(warmup_before_measure)),
        _bash_env_line("GE_RUNTIME_WARMUP_PROMPT_ID", warmup_prompt_id),
        _bash_env_line("GE_RUNTIME_WAIT_FOR_READY_LOG", int(wait_for_ready_log)),
        _bash_env_line("GE_RUNTIME_READY_LOG_PATTERN", metadata["ready_log_pattern"]),
        _bash_env_line("GE_RUNTIME_SERVER_START_TIMEOUT", runtime["timeouts"]["server_start"]),
        _bash_env_line("GE_RUNTIME_REQUEST_TIMEOUT", runtime["timeouts"]["request"]),
        _bash_env_line("GE_RUNTIME_AFTER_REQUEST_SLEEP", runtime["timeouts"]["after_request_sleep"]),
        _bash_env_line("GE_RUNTIME_AFTER_WARMUP_SLEEP", runtime["timeouts"]["after_warmup_sleep"]),
        _bash_env_line("GE_RUNTIME_KEEP_SERVER_AFTER_REUSE", int(runtime["control"]["keep_server_after_reuse"])),
        _bash_env_line("GE_RUNTIME_KEEP_LMCACHE_MP_AFTER_RUN", int(runtime["control"]["keep_lmcache_mp_after_run"])),
        _bash_env_line("GE_RUNTIME_LMCACHE_BIN", runtime["tools"]["lmcache"]),
        _bash_env_line("GE_RUNTIME_VLLM_BIN", runtime["tools"]["vllm"]),
        _bash_env_line("GE_RUNTIME_LMCACHE_LOG_LEVEL", _env("LMCACHE_LOG_LEVEL", "DEBUG")),
        _bash_env_line("GE_RUNTIME_LMCACHE_MP_HOST", metadata["lmcache_mp"]["host"]),
        _bash_env_line("GE_RUNTIME_LMCACHE_MP_PORT", metadata["lmcache_mp"]["port"]),
        _bash_env_line("GE_RUNTIME_LMCACHE_MP_HTTP_HOST", metadata["lmcache_mp"]["http_host"]),
        _bash_env_line("GE_RUNTIME_LMCACHE_MP_PROMETHEUS_PORT", metadata["lmcache_mp"]["prometheus_port"]),
    ]
    Path(paths["runtime_env"]).write_text("\n".join(env_lines) + "\n", encoding="utf-8")
    print(paths["runtime_env"])
    return 0


def print_args(args: argparse.Namespace) -> int:
    runtime = _runtime_load(Path(args.runtime))
    for value in runtime["commands"][args.name]:
        print(value)
    return 0


def print_field(args: argparse.Namespace) -> int:
    runtime = _runtime_load(Path(args.runtime))
    value = _runtime_get(runtime, args.key)
    if isinstance(value, (dict, list)):
        print(json.dumps(value, sort_keys=True))
    else:
        print(value)
    return 0


def tcp_wait(args: argparse.Namespace) -> int:
    host = args.host
    if host.startswith("tcp://"):
        host = host[len("tcp://") :]
    deadline = time.time() + args.timeout
    while time.time() < deadline:
        try:
            with socket.create_connection((host, args.port), timeout=2):
                return 0
        except OSError:
            time.sleep(args.interval)
    return 1


def mark_log(args: argparse.Namespace) -> int:
    runtime = _runtime_load(Path(args.runtime))
    log_dir = Path(runtime["paths"]["log_dir"])
    source = log_dir / "lmcache_mp_server.log"
    offset = source.stat().st_size if source.exists() else 0
    Path(runtime["paths"]["run_dir"], f"{args.phase}_lmcache_log_offset.txt").write_text(
        str(offset),
        encoding="utf-8",
    )
    return 0


def capture_log(args: argparse.Namespace) -> int:
    runtime = _runtime_load(Path(args.runtime))
    log_dir = Path(runtime["paths"]["log_dir"])
    run_dir = Path(runtime["paths"]["run_dir"])
    source = log_dir / "lmcache_mp_server.log"
    dest = log_dir / f"{args.phase}_lmcache_mp_server.log"
    offset_path = run_dir / f"{args.phase}_lmcache_log_offset.txt"
    if not source.exists():
        return 0
    offset = int(offset_path.read_text(encoding="utf-8").strip() or "0") if offset_path.exists() else 0
    with source.open("rb") as handle:
        handle.seek(max(0, offset))
        data = handle.read()
    dest.write_bytes(data)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    prepare_parser = subparsers.add_parser("prepare")
    prepare_parser.add_argument("--repo-root", default=".")
    prepare_parser.add_argument("engine_args", nargs=argparse.REMAINDER)
    prepare_parser.set_defaults(func=prepare)

    args_parser = subparsers.add_parser("args")
    args_parser.add_argument("--runtime", required=True)
    args_parser.add_argument("name", choices=["lmcache", "vllm", "sglang-legacy"])
    args_parser.set_defaults(func=print_args)

    field_parser = subparsers.add_parser("field")
    field_parser.add_argument("--runtime", required=True)
    field_parser.add_argument("key")
    field_parser.set_defaults(func=print_field)

    wait_parser = subparsers.add_parser("tcp-wait")
    wait_parser.add_argument("--host", required=True)
    wait_parser.add_argument("--port", required=True, type=int)
    wait_parser.add_argument("--timeout", required=True, type=float)
    wait_parser.add_argument("--interval", type=float, default=1.0)
    wait_parser.set_defaults(func=tcp_wait)

    mark_parser = subparsers.add_parser("mark-log")
    mark_parser.add_argument("--runtime", required=True)
    mark_parser.add_argument("--phase", required=True)
    mark_parser.set_defaults(func=mark_log)

    capture_parser = subparsers.add_parser("capture-log")
    capture_parser.add_argument("--runtime", required=True)
    capture_parser.add_argument("--phase", required=True)
    capture_parser.set_defaults(func=capture_log)

    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
