"""Same-model different-parameter-size KV reuse support."""

from goldenexperience.size_variant.calibration import (
    QWEN3_14B,
    QWEN3_8B,
    build_calibration_manifest,
    load_prompt_count,
    qwen3_model_pair,
    save_prompt_manifest,
)
from goldenexperience.size_variant.layer_mapping import build_linear_layer_map
from goldenexperience.size_variant.models import (
    CalibrationManifest,
    FallbackReason,
    HiddenBridgeSpec,
    KVRestoreSpec,
    LayerMap,
    LayerMapEntry,
    ProjectionSpec,
    QualityGateResult,
    SizeVariantDirection,
    infer_direction,
    kv_width,
    pair_id_for,
)
from goldenexperience.size_variant.projection import (
    HiddenBridgeMaterializer,
    HiddenStateChunk,
    KVChunk,
    MaterializationResult,
    MaterializedHiddenChunk,
    MaterializedKVChunk,
    SizeVariantMaterializer,
    TargetKVRestorer,
    build_hidden_bridge_spec,
    build_kv_restore_spec,
    build_projection_spec,
    validate_projection_cost,
)

__all__ = [
    "CalibrationManifest",
    "FallbackReason",
    "HiddenBridgeMaterializer",
    "HiddenBridgeSpec",
    "HiddenStateChunk",
    "KVChunk",
    "KVRestoreSpec",
    "LayerMap",
    "LayerMapEntry",
    "MaterializationResult",
    "MaterializedHiddenChunk",
    "MaterializedKVChunk",
    "ProjectionSpec",
    "QWEN3_14B",
    "QWEN3_8B",
    "QualityGateResult",
    "SizeVariantDirection",
    "SizeVariantMaterializer",
    "TargetKVRestorer",
    "build_calibration_manifest",
    "build_hidden_bridge_spec",
    "build_kv_restore_spec",
    "build_linear_layer_map",
    "build_projection_spec",
    "infer_direction",
    "kv_width",
    "load_prompt_count",
    "pair_id_for",
    "qwen3_model_pair",
    "save_prompt_manifest",
    "validate_projection_cost",
]
