"""Same-model different-parameter-size KV reuse support."""

from goldenexperience.size_variant.cached_kv_bridge import (
    CachedKVBridgeError,
    Qwen3CachedKVBridge,
    safetensors_metadata,
)
from goldenexperience.size_variant.cached_kv_dataset import (
    CACHED_KV_DATASET_SCHEMA_VERSION,
    CachedKVPrompt,
    CachedKVPromptDataset,
    contains_expected_final_answer,
    render_to_token_bucket,
)
from goldenexperience.size_variant.cached_kv_manifest import (
    CACHED_KV_SCHEMA_VERSION,
    CachedKVBridgeManifest,
    CachedKVModelSpec,
    CachedKVQualityEvidence,
    CachedKVQualityThresholds,
    artifact_id_for,
    model_spec_from_path,
)
from goldenexperience.size_variant.cached_kv_training import (
    build_source_layer_plan,
    build_training_matrices,
    cache_to_object,
    fit_low_rank_state,
    object_to_dynamic_cache,
    transform_with_state,
)
from goldenexperience.size_variant.calibration import (
    QWEN3_8B,
    QWEN3_14B,
    build_calibration_manifest,
    load_prompt_count,
    qwen3_model_pair,
    save_prompt_manifest,
)
from goldenexperience.size_variant.layer_mapping import build_linear_layer_map
from goldenexperience.size_variant.models import (
    CalibrationManifest,
    FallbackReason,
    HiddenBridgeSpec,
    KVRestoreSpec,
    LayerMap,
    LayerMapEntry,
    ProjectionSpec,
    QualityGateResult,
    SizeVariantDirection,
    infer_direction,
    kv_width,
    pair_id_for,
)
from goldenexperience.size_variant.projection import (
    HiddenBridgeMaterializer,
    HiddenStateChunk,
    KVChunk,
    MaterializationResult,
    MaterializedHiddenChunk,
    MaterializedKVChunk,
    SizeVariantMaterializer,
    TargetKVRestorer,
    build_hidden_bridge_spec,
    build_kv_restore_spec,
    build_projection_spec,
    validate_projection_cost,
)

__all__ = [
    "CACHED_KV_SCHEMA_VERSION",
    "CACHED_KV_DATASET_SCHEMA_VERSION",
    "CalibrationManifest",
    "CachedKVBridgeError",
    "CachedKVBridgeManifest",
    "CachedKVModelSpec",
    "CachedKVPrompt",
    "CachedKVPromptDataset",
    "CachedKVQualityEvidence",
    "CachedKVQualityThresholds",
    "FallbackReason",
    "HiddenBridgeMaterializer",
    "HiddenBridgeSpec",
    "HiddenStateChunk",
    "KVChunk",
    "KVRestoreSpec",
    "LayerMap",
    "LayerMapEntry",
    "MaterializationResult",
    "MaterializedHiddenChunk",
    "MaterializedKVChunk",
    "ProjectionSpec",
    "QWEN3_14B",
    "QWEN3_8B",
    "Qwen3CachedKVBridge",
    "QualityGateResult",
    "SizeVariantDirection",
    "SizeVariantMaterializer",
    "TargetKVRestorer",
    "build_calibration_manifest",
    "build_hidden_bridge_spec",
    "build_kv_restore_spec",
    "build_linear_layer_map",
    "build_projection_spec",
    "build_source_layer_plan",
    "build_training_matrices",
    "cache_to_object",
    "contains_expected_final_answer",
    "artifact_id_for",
    "infer_direction",
    "fit_low_rank_state",
    "kv_width",
    "load_prompt_count",
    "pair_id_for",
    "qwen3_model_pair",
    "model_spec_from_path",
    "object_to_dynamic_cache",
    "render_to_token_bucket",
    "safetensors_metadata",
    "save_prompt_manifest",
    "validate_projection_cost",
    "transform_with_state",
]
