"""Prompt manifest generation for KV baseline runs."""

from __future__ import annotations

import json

from goldenexperience.runtime.kv_baseline.config import BaselineConfig


def write_generated_disk_prompt(config: BaselineConfig) -> None:
    """Generate a deterministic long-prefix prompt when disk evidence is required."""

    if not config.force_disk_offload or config.prompt_file_was_set:
        return

    lines = []
    for i in range(config.disk_prompt_repeat):
        lines.append(
            f"Cache persistence calibration line {i:04d}: "
            "GoldenExperience disk-offload validation keeps this deterministic prefix stable. "
            "Natalia April clips equals 48 and May clips equals half of April. "
            "This repeated text exists only to make the prompt large enough for KV caching."
        )

    user_content = (
        "Read the following deterministic reference block. Do not summarize the block.\n\n"
        + "\n".join(lines)
        + "\n\nQuestion: Natalia sold clips to 48 of her friends in April, and then she sold "
        "half as many clips in May. How many clips did Natalia sell altogether in April "
        "and May? End with exactly one line formatted as: Final answer: <number>."
    )

    manifest = {
        "default_prompt_id": config.disk_prompt_id,
        "prompts": [
            {
                "id": config.disk_prompt_id,
                "dataset": "synthetic-long-prefix",
                "split": "disk-offload",
                "source": "generated by goldenexperience.runtime.kv_baseline",
                "expected_final_answer": "72",
                "messages": [
                    {
                        "role": "system",
                        "content": (
                            "You are a careful math solver. Use the reference only as context."
                        ),
                    },
                    {"role": "user", "content": user_content},
                ],
                "generation": {
                    "max_tokens": config.disk_prompt_max_tokens,
                    "temperature": 0,
                },
            },
            {
                "id": config.warmup_prompt_id,
                "dataset": "synthetic",
                "split": "warmup",
                "source": "short unrelated warmup prompt for engine stabilization",
                "expected_final_answer": "OK",
                "messages": [
                    {"role": "system", "content": "You are a concise assistant."},
                    {"role": "user", "content": "Reply with exactly: OK"},
                ],
                "generation": {"max_tokens": 8, "temperature": 0},
            },
        ],
    }
    config.prompt_file.parent.mkdir(parents=True, exist_ok=True)
    config.prompt_file.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
